version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    networks:
      - default
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=laravel_app
      - DB_USERNAME=user
      - DB_PASSWORD=your_password
    depends_on:
      - database
    ports:
      - "${APP_PORT}:9000"

  webserver:
    image: nginx:latest
    ports:
      - "${WEBSERVER_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: your_password
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
